insert into contacts (name) values ('Lorrayne Spoole'),
('Jessalin OQuin'),
('Theodor Blaskett'),
('Sigismundo Fidock'),
('Hamlin Liebermann'),
('Raymund Thomasen'),
('Vittorio Iacovino'),
('Coralie Elloy'),
('Irvine Carnalan'),
('Ethyl Stanbridge'),
('Margalo Trasler'),
('Niall Estabrook'),
('Krispin Stockwell');